name: eqboard38
chanels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - requests
  - numpy=1.19
  - pandas
  - scikit-learn
  - matplotlib
  - dash
  - plotly
  - pywavelets
  - tqdm
  - pyarrow
  - gunicorn
  - tensorflow
  - h5py